#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BeGenerous.Resource", IsApplication=true)]

namespace BeGenerous
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_open_inbox = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_send_gift = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_send_request = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060005
			public const int avatar = 2131099653;
			
			// aapt resource value: 0x7f06000a
			public const int button_open_inbox = 2131099658;
			
			// aapt resource value: 0x7f060008
			public const int button_send_gift = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int button_send_request = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int button_sign_in = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int button_sign_out = 2131099662;
			
			// aapt resource value: 0x7f060003
			public const int imageViewReceiveGift = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int imageViewSendGift = 2131099650;
			
			// aapt resource value: 0x7f060007
			public const int playerEmail = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int playerName = 2131099654;
			
			// aapt resource value: 0x7f06000b
			public const int sign_in_bar = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int sign_out_bar = 2131099661;
			
			// aapt resource value: 0x7f060000
			public const int status_area = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int tv_gift_count = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int tv_request_count = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_id = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int app_name = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int click_me = 2130968583;
			
			// aapt resource value: 0x7f040016
			public const int gift_count = 2130968598;
			
			// aapt resource value: 0x7f040014
			public const int gift_icon_description = 2130968596;
			
			// aapt resource value: 0x7f04000f
			public const int gift_toast = 2130968591;
			
			// aapt resource value: 0x7f040012
			public const int inbox_counts = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int loading_ellipsis = 2130968595;
			
			// aapt resource value: 0x7f040010
			public const int new_gift_received = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int new_request_received = 2130968593;
			
			// aapt resource value: 0x7f04000a
			public const int open_inbox = 2130968586;
			
			// aapt resource value: 0x7f040017
			public const int request_count = 2130968599;
			
			// aapt resource value: 0x7f040015
			public const int request_icon_description = 2130968597;
			
			// aapt resource value: 0x7f04000b
			public const int send_gift = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int send_gift_description = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int send_request = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int send_request_description = 2130968590;
			
			// aapt resource value: 0x7f040004
			public const int sign_in_explanation = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int sign_out = 2130968582;
			
			// aapt resource value: 0x7f040018
			public const int signin_other_error = 2130968600;
			
			// aapt resource value: 0x7f040001
			public const int signing_in = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int signing_out = 2130968578;
			
			// aapt resource value: 0x7f040008
			public const int victory = 2130968584;
			
			// aapt resource value: 0x7f040005
			public const int you_are_signed_in = 2130968581;
			
			// aapt resource value: 0x7f040009
			public const int you_won = 2130968585;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int AppBaseTheme = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int AppTheme = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int Button = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int MainDisplay = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int MainLayout = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int SignInButton = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int SignInOutBar = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int SignInOutBarBlurb = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int SignOutButton = 2131034117;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
